In [71]:
import pandas as pd

In [72]:
df = pd.read_csv("data//Kittchen.csv")

In [73]:
df.head()

,MONTH,CITY,STORE,STATUS,ZONE MAPPING,ORDER COUNT,CART SALES,DISCOUNT,NET REVENUE,IDEAL FOOD COST,GROSS MARGIN,KITCHEN EBITDA,VARIANCE,REVENUE COHORT,CM COHORT,EBITDA CATEGORY,EBITDA COHORT
0,Oct-23,Ahmedabad,Ramos-Martin,Inactive,West,14270,6554333.68,1163493.98,5434068.17,1763679.62,3614747.39,2374914.55,29664.62,INR 20 to 30 lacs,0% to 10%,EBITDA +ve,More than 20%
1,Nov-23,Ahmedabad,Ramos-Martin,Inactive,West,8528,2637625.82,636015.27,2146679.55,638415.30,1414249.00,151761.82,11769.85,INR 20 to 30 lacs,More than 30%,EBITDA +ve,More than 20%
2,Dec-23,Ahmedabad,Ramos-Martin,Inactive,West,10798,4364193.67,1283840.18,3188606.71,1085080.58,2036999.44,736811.76,23376.83,INR 30 to 40 lacs,0% to 10%,EBITDA +ve,0% to 10%
3,Jan-24,Ahmedabad,Ramos-Martin,Inactive,West,7804,3479969.32,854797.46,2734306.33,1180892.50,1451140.55,229924.26,26162.41,INR 20 to 30 lacs,0% to 10%,EBITDA +ve,More than 20%
4,Feb-24,Ahmedabad,Ramos-Martin,Inactive,West,10060,4771378.71,1290900.38,3602124.88,1114846.94,2394567.16,1114151.65,19944.97,INR 20 to 30 lacs,More than 30%,EBITDA -ve,0% to 10%

In [74]:
df.describe()

,ORDER COUNT,CART SALES,DISCOUNT,NET REVENUE,IDEAL FOOD COST,GROSS MARGIN,KITCHEN EBITDA,VARIANCE
count,2100.000000,2.100000e+03,2.100000e+03,2.100000e+03,2.100000e+03,2.100000e+03,2.100000e+03,2100.000000
mean,11045.371905,4.400591e+06,9.839992e+05,3.505318e+06,1.362716e+06,2.043380e+06,6.847230e+05,20176.588981
std,2290.859134,1.119388e+06,3.136288e+05,8.948390e+05,4.151767e+05,5.724239e+05,5.810918e+05,5783.204330
min,7002.000000,2.177493e+06,3.521976e+05,1.726080e+06,5.567911e+05,8.628336e+05,-5.858504e+05,10018.480000
25%,9097.000000,3.520108e+06,7.442392e+05,2.817943e+06,1.059971e+06,1.612744e+06,2.520450e+05,15494.855000
50%,10987.000000,4.295395e+06,9.388061e+05,3.427512e+06,1.298579e+06,1.980660e+06,6.176177e+05,20195.190000
75%,12986.750000,5.184657e+06,1.176024e+06,4.127204e+06,1.618120e+06,2.423338e+06,1.076676e+06,25180.827500
max,14999.000000,7.471638e+06,2.147224e+06,6.167425e+06,2.797857e+06,4.172730e+06,2.834680e+06,29993.940000

In [75]:
df.isnull().sum()

MONTH              0
CITY               0
STORE              0
STATUS             0
ZONE MAPPING       0
ORDER COUNT        0
CART SALES         0
DISCOUNT           0
NET REVENUE        0
IDEAL FOOD COST    0
GROSS MARGIN       0
KITCHEN EBITDA     0
VARIANCE           0
REVENUE COHORT     0
CM COHORT          0
EBITDA CATEGORY    0
EBITDA COHORT      0
dtype: int64

In [76]:
df["MONTH"] = pd.to_datetime(df["MONTH"],format="%b-%y")
df.head()

,MONTH,CITY,STORE,STATUS,ZONE MAPPING,ORDER COUNT,CART SALES,DISCOUNT,NET REVENUE,IDEAL FOOD COST,GROSS MARGIN,KITCHEN EBITDA,VARIANCE,REVENUE COHORT,CM COHORT,EBITDA CATEGORY,EBITDA COHORT
0,2023-10-01,Ahmedabad,Ramos-Martin,Inactive,West,14270,6554333.68,1163493.98,5434068.17,1763679.62,3614747.39,2374914.55,29664.62,INR 20 to 30 lacs,0% to 10%,EBITDA +ve,More than 20%
1,2023-11-01,Ahmedabad,Ramos-Martin,Inactive,West,8528,2637625.82,636015.27,2146679.55,638415.30,1414249.00,151761.82,11769.85,INR 20 to 30 lacs,More than 30%,EBITDA +ve,More than 20%
2,2023-12-01,Ahmedabad,Ramos-Martin,Inactive,West,10798,4364193.67,1283840.18,3188606.71,1085080.58,2036999.44,736811.76,23376.83,INR 30 to 40 lacs,0% to 10%,EBITDA +ve,0% to 10%
3,2024-01-01,Ahmedabad,Ramos-Martin,Inactive,West,7804,3479969.32,854797.46,2734306.33,1180892.50,1451140.55,229924.26,26162.41,INR 20 to 30 lacs,0% to 10%,EBITDA +ve,More than 20%
4,2024-02-01,Ahmedabad,Ramos-Martin,Inactive,West,10060,4771378.71,1290900.38,3602124.88,1114846.94,2394567.16,1114151.65,19944.97,INR 20 to 30 lacs,More than 30%,EBITDA -ve,0% to 10%

In [77]:
df = df.sort_values("MONTH")
df.head()

,MONTH,CITY,STORE,STATUS,ZONE MAPPING,ORDER COUNT,CART SALES,DISCOUNT,NET REVENUE,IDEAL FOOD COST,GROSS MARGIN,KITCHEN EBITDA,VARIANCE,REVENUE COHORT,CM COHORT,EBITDA CATEGORY,EBITDA COHORT
0,2023-10-01,Ahmedabad,Ramos-Martin,Inactive,West,14270,6554333.68,1163493.98,5434068.17,1763679.62,3614747.39,2374914.55,29664.62,INR 20 to 30 lacs,0% to 10%,EBITDA +ve,More than 20%
342,2023-10-01,Ahmedabad,Drake LLC,Active,North,12361,3971544.22,888746.33,3158828.94,1271805.20,1822334.08,252214.75,17982.19,INR 30 to 40 lacs,More than 30%,EBITDA -ve,More than 20%
918,2023-10-01,Pune,"Thomas, Dean and Kelley",Inactive,East,11021,4202495.56,1123306.62,3196270.28,1372216.47,1700911.62,301105.29,20263.87,INR 30 to 40 lacs,More than 30%,EBITDA -ve,More than 20%
1944,2023-10-01,Hyderabad,Smith-Bradley,Inactive,West,12706,5709492.69,1513926.48,4279244.35,1840266.70,2328502.65,1137049.92,26410.24,INR 30 to 40 lacs,10% to 20%,EBITDA +ve,10% to 20%
924,2023-10-01,Hyderabad,Stone Ltd,Active,South,14760,4960664.78,889983.70,4150072.32,1721686.18,2361360.65,1107156.67,18967.00,More than 40 lacs,0% to 10%,EBITDA +ve,10% to 20%

In [78]:
df["GM_PCT"]=(df["GROSS MARGIN"]/df["NET REVENUE"])*100
df.head()

,MONTH,CITY,STORE,STATUS,ZONE MAPPING,ORDER COUNT,CART SALES,DISCOUNT,NET REVENUE,IDEAL FOOD COST,GROSS MARGIN,KITCHEN EBITDA,VARIANCE,REVENUE COHORT,CM COHORT,EBITDA CATEGORY,EBITDA COHORT,GM_PCT
0,2023-10-01,Ahmedabad,Ramos-Martin,Inactive,West,14270,6554333.68,1163493.98,5434068.17,1763679.62,3614747.39,2374914.55,29664.62,INR 20 to 30 lacs,0% to 10%,EBITDA +ve,More than 20%,66.520096
342,2023-10-01,Ahmedabad,Drake LLC,Active,North,12361,3971544.22,888746.33,3158828.94,1271805.20,1822334.08,252214.75,17982.19,INR 30 to 40 lacs,More than 30%,EBITDA -ve,More than 20%,57.690179
918,2023-10-01,Pune,"Thomas, Dean and Kelley",Inactive,East,11021,4202495.56,1123306.62,3196270.28,1372216.47,1700911.62,301105.29,20263.87,INR 30 to 40 lacs,More than 30%,EBITDA -ve,More than 20%,53.215513
1944,2023-10-01,Hyderabad,Smith-Bradley,Inactive,West,12706,5709492.69,1513926.48,4279244.35,1840266.70,2328502.65,1137049.92,26410.24,INR 30 to 40 lacs,10% to 20%,EBITDA +ve,10% to 20%,54.413874
924,2023-10-01,Hyderabad,Stone Ltd,Active,South,14760,4960664.78,889983.70,4150072.32,1721686.18,2361360.65,1107156.67,18967.00,More than 40 lacs,0% to 10%,EBITDA +ve,10% to 20%,56.899265

In [79]:
df["EBITDA_PCT"]=(df["KITCHEN EBITDA"]/df["NET REVENUE"])*100
df.head()

,MONTH,CITY,STORE,STATUS,ZONE MAPPING,ORDER COUNT,CART SALES,DISCOUNT,NET REVENUE,IDEAL FOOD COST,GROSS MARGIN,KITCHEN EBITDA,VARIANCE,REVENUE COHORT,CM COHORT,EBITDA CATEGORY,EBITDA COHORT,GM_PCT,EBITDA_PCT
0,2023-10-01,Ahmedabad,Ramos-Martin,Inactive,West,14270,6554333.68,1163493.98,5434068.17,1763679.62,3614747.39,2374914.55,29664.62,INR 20 to 30 lacs,0% to 10%,EBITDA +ve,More than 20%,66.520096,43.704173
342,2023-10-01,Ahmedabad,Drake LLC,Active,North,12361,3971544.22,888746.33,3158828.94,1271805.20,1822334.08,252214.75,17982.19,INR 30 to 40 lacs,More than 30%,EBITDA -ve,More than 20%,57.690179,7.984438
918,2023-10-01,Pune,"Thomas, Dean and Kelley",Inactive,East,11021,4202495.56,1123306.62,3196270.28,1372216.47,1700911.62,301105.29,20263.87,INR 30 to 40 lacs,More than 30%,EBITDA -ve,More than 20%,53.215513,9.420520
1944,2023-10-01,Hyderabad,Smith-Bradley,Inactive,West,12706,5709492.69,1513926.48,4279244.35,1840266.70,2328502.65,1137049.92,26410.24,INR 30 to 40 lacs,10% to 20%,EBITDA +ve,10% to 20%,54.413874,26.571278
924,2023-10-01,Hyderabad,Stone Ltd,Active,South,14760,4960664.78,889983.70,4150072.32,1721686.18,2361360.65,1107156.67,18967.00,More than 40 lacs,0% to 10%,EBITDA +ve,10% to 20%,56.899265,26.678009

In [80]:
df["AOV"]=(df["NET REVENUE"]/df["ORDER COUNT"])

In [81]:
df["VARIANCE_PCT"]=(df["VARIANCE"]/df["IDEAL FOOD COST"])*100

In [82]:
df["VARIANCE_PCT"].describe()

count    2100.000000
mean        1.625498
std         0.705677
min         0.379547
25%         1.106865
50%         1.511681
75%         2.015820
max         4.714317
Name: VARIANCE_PCT, dtype: float64

In [83]:
df["VARIANCE_PCT"].describe()

count    2100.000000
mean        1.625498
std         0.705677
min         0.379547
25%         1.106865
50%         1.511681
75%         2.015820
max         4.714317
Name: VARIANCE_PCT, dtype: float64

In [84]:
variance_bins = [0, 2, 3, 5, 100]
variance_labels = ["Var <2%","Var 2%-3%","Var 3%-5%","Var >5%"]
df["VARIANCE_CATEGORY"] = pd.cut(df["VARIANCE_PCT"],bins=variance_bins,labels=variance_labels,include_lowest=True)

In [85]:
df.head()

,MONTH,CITY,STORE,STATUS,ZONE MAPPING,ORDER COUNT,CART SALES,DISCOUNT,NET REVENUE,IDEAL FOOD COST,...,VARIANCE,REVENUE COHORT,CM COHORT,EBITDA CATEGORY,EBITDA COHORT,GM_PCT,EBITDA_PCT,AOV,VARIANCE_PCT,VARIANCE_CATEGORY
0,2023-10-01,Ahmedabad,Ramos-Martin,Inactive,West,14270,6554333.68,1163493.98,5434068.17,1763679.62,...,29664.62,INR 20 to 30 lacs,0% to 10%,EBITDA +ve,More than 20%,66.520096,43.704173,380.803656,1.681973,Var <2%
342,2023-10-01,Ahmedabad,Drake LLC,Active,North,12361,3971544.22,888746.33,3158828.94,1271805.20,...,17982.19,INR 30 to 40 lacs,More than 30%,EBITDA -ve,More than 20%,57.690179,7.984438,255.548009,1.413911,Var <2%
918,2023-10-01,Pune,"Thomas, Dean and Kelley",Inactive,East,11021,4202495.56,1123306.62,3196270.28,1372216.47,...,20263.87,INR 30 to 40 lacs,More than 30%,EBITDA -ve,More than 20%,53.215513,9.420520,290.016358,1.476725,Var <2%
1944,2023-10-01,Hyderabad,Smith-Bradley,Inactive,West,12706,5709492.69,1513926.48,4279244.35,1840266.70,...,26410.24,INR 30 to 40 lacs,10% to 20%,EBITDA +ve,10% to 20%,54.413874,26.571278,336.789261,1.435131,Var <2%
924,2023-10-01,Hyderabad,Stone Ltd,Active,South,14760,4960664.78,889983.70,4150072.32,1721686.18,...,18967.00,More than 40 lacs,0% to 10%,EBITDA +ve,10% to 20%,56.899265,26.678009,281.170211,1.101653,Var <2%

In [86]:
df["VARIANCE_CATEGORY"].value_counts()
df.head()

,MONTH,CITY,STORE,STATUS,ZONE MAPPING,ORDER COUNT,CART SALES,DISCOUNT,NET REVENUE,IDEAL FOOD COST,...,VARIANCE,REVENUE COHORT,CM COHORT,EBITDA CATEGORY,EBITDA COHORT,GM_PCT,EBITDA_PCT,AOV,VARIANCE_PCT,VARIANCE_CATEGORY
0,2023-10-01,Ahmedabad,Ramos-Martin,Inactive,West,14270,6554333.68,1163493.98,5434068.17,1763679.62,...,29664.62,INR 20 to 30 lacs,0% to 10%,EBITDA +ve,More than 20%,66.520096,43.704173,380.803656,1.681973,Var <2%
342,2023-10-01,Ahmedabad,Drake LLC,Active,North,12361,3971544.22,888746.33,3158828.94,1271805.20,...,17982.19,INR 30 to 40 lacs,More than 30%,EBITDA -ve,More than 20%,57.690179,7.984438,255.548009,1.413911,Var <2%
918,2023-10-01,Pune,"Thomas, Dean and Kelley",Inactive,East,11021,4202495.56,1123306.62,3196270.28,1372216.47,...,20263.87,INR 30 to 40 lacs,More than 30%,EBITDA -ve,More than 20%,53.215513,9.420520,290.016358,1.476725,Var <2%
1944,2023-10-01,Hyderabad,Smith-Bradley,Inactive,West,12706,5709492.69,1513926.48,4279244.35,1840266.70,...,26410.24,INR 30 to 40 lacs,10% to 20%,EBITDA +ve,10% to 20%,54.413874,26.571278,336.789261,1.435131,Var <2%
924,2023-10-01,Hyderabad,Stone Ltd,Active,South,14760,4960664.78,889983.70,4150072.32,1721686.18,...,18967.00,More than 40 lacs,0% to 10%,EBITDA +ve,10% to 20%,56.899265,26.678009,281.170211,1.101653,Var <2%

In [87]:
df["DISCOUNT_PCT"]=(df["DISCOUNT"]/df["CART SALES"])*100
df.head()

,MONTH,CITY,STORE,STATUS,ZONE MAPPING,ORDER COUNT,CART SALES,DISCOUNT,NET REVENUE,IDEAL FOOD COST,...,REVENUE COHORT,CM COHORT,EBITDA CATEGORY,EBITDA COHORT,GM_PCT,EBITDA_PCT,AOV,VARIANCE_PCT,VARIANCE_CATEGORY,DISCOUNT_PCT
0,2023-10-01,Ahmedabad,Ramos-Martin,Inactive,West,14270,6554333.68,1163493.98,5434068.17,1763679.62,...,INR 20 to 30 lacs,0% to 10%,EBITDA +ve,More than 20%,66.520096,43.704173,380.803656,1.681973,Var <2%,17.751522
342,2023-10-01,Ahmedabad,Drake LLC,Active,North,12361,3971544.22,888746.33,3158828.94,1271805.20,...,INR 30 to 40 lacs,More than 30%,EBITDA -ve,More than 20%,57.690179,7.984438,255.548009,1.413911,Var <2%,22.377853
918,2023-10-01,Pune,"Thomas, Dean and Kelley",Inactive,East,11021,4202495.56,1123306.62,3196270.28,1372216.47,...,INR 30 to 40 lacs,More than 30%,EBITDA -ve,More than 20%,53.215513,9.420520,290.016358,1.476725,Var <2%,26.729514
1944,2023-10-01,Hyderabad,Smith-Bradley,Inactive,West,12706,5709492.69,1513926.48,4279244.35,1840266.70,...,INR 30 to 40 lacs,10% to 20%,EBITDA +ve,10% to 20%,54.413874,26.571278,336.789261,1.435131,Var <2%,26.515954
924,2023-10-01,Hyderabad,Stone Ltd,Active,South,14760,4960664.78,889983.70,4150072.32,1721686.18,...,More than 40 lacs,0% to 10%,EBITDA +ve,10% to 20%,56.899265,26.678009,281.170211,1.101653,Var <2%,17.940815

In [88]:
#Exploratory Data Analysis

In [89]:
##Reven Trends
df.groupby("MONTH")["NET REVENUE"].sum()

MONTH
2023-10-01    1.240710e+09
2023-11-01    1.215371e+09
2023-12-01    1.211609e+09
2024-01-01    1.247391e+09
2024-02-01    1.213152e+09
2024-03-01    1.232936e+09
Name: NET REVENUE, dtype: float64

In [90]:
#Best Cities
df.groupby("CITY")["KITCHEN EBITDA"].sum()

CITY
Ahmedabad    3.740616e+08
Bangalore    2.812729e+08
Hyderabad    2.984644e+08
Mumbai       2.399434e+08
Pune         2.441761e+08
Name: KITCHEN EBITDA, dtype: float64

In [91]:
#worst stores
df.groupby("STORE")["KITCHEN EBITDA"].sum().sort_values()

STORE
Andrews, Reed and Silva         -779236.85
Bowman-Martinez                  517367.27
Hansen, Delgado and Bennett      658163.51
Wright, Floyd and Taylor         854224.27
Thomas LLC                       979098.09
                                  ...
Sanchez and Sons                9167939.50
Jimenez LLC                     9170224.04
Sanders Ltd                    11702593.79
Adams LLC                      11720624.21
Smith Ltd                      12096497.47
Name: KITCHEN EBITDA, Length: 344, dtype: float64

In [92]:
##High Variance Stores
df.groupby("STORE")["VARIANCE_PCT"].mean()

STORE
Acevedo Inc                      1.608628
Adams LLC                        1.362063
Aguilar, Becker and Hernandez    1.870672
Aguirre-Goodman                  1.453206
Allen Group                      1.685365
                                   ...
Wood, Vasquez and Garcia         1.386445
Woodard, Dominguez and Miller    1.559215
Wright, Floyd and Taylor         1.994714
Wright-Massey                    1.459624
Young Ltd                        1.575890
Name: VARIANCE_PCT, Length: 344, dtype: float64

In [93]:
df.head()

,MONTH,CITY,STORE,STATUS,ZONE MAPPING,ORDER COUNT,CART SALES,DISCOUNT,NET REVENUE,IDEAL FOOD COST,...,REVENUE COHORT,CM COHORT,EBITDA CATEGORY,EBITDA COHORT,GM_PCT,EBITDA_PCT,AOV,VARIANCE_PCT,VARIANCE_CATEGORY,DISCOUNT_PCT
0,2023-10-01,Ahmedabad,Ramos-Martin,Inactive,West,14270,6554333.68,1163493.98,5434068.17,1763679.62,...,INR 20 to 30 lacs,0% to 10%,EBITDA +ve,More than 20%,66.520096,43.704173,380.803656,1.681973,Var <2%,17.751522
342,2023-10-01,Ahmedabad,Drake LLC,Active,North,12361,3971544.22,888746.33,3158828.94,1271805.20,...,INR 30 to 40 lacs,More than 30%,EBITDA -ve,More than 20%,57.690179,7.984438,255.548009,1.413911,Var <2%,22.377853
918,2023-10-01,Pune,"Thomas, Dean and Kelley",Inactive,East,11021,4202495.56,1123306.62,3196270.28,1372216.47,...,INR 30 to 40 lacs,More than 30%,EBITDA -ve,More than 20%,53.215513,9.420520,290.016358,1.476725,Var <2%,26.729514
1944,2023-10-01,Hyderabad,Smith-Bradley,Inactive,West,12706,5709492.69,1513926.48,4279244.35,1840266.70,...,INR 30 to 40 lacs,10% to 20%,EBITDA +ve,10% to 20%,54.413874,26.571278,336.789261,1.435131,Var <2%,26.515954
924,2023-10-01,Hyderabad,Stone Ltd,Active,South,14760,4960664.78,889983.70,4150072.32,1721686.18,...,More than 40 lacs,0% to 10%,EBITDA +ve,10% to 20%,56.899265,26.678009,281.170211,1.101653,Var <2%,17.940815

In [94]:
df.to_csv("data/processed_kitchen_pnl.csv",index=False)

In [95]:
cd=pd.read_csv("data/processed_kitchen_pnl.csv")
cd.head()

,MONTH,CITY,STORE,STATUS,ZONE MAPPING,ORDER COUNT,CART SALES,DISCOUNT,NET REVENUE,IDEAL FOOD COST,...,REVENUE COHORT,CM COHORT,EBITDA CATEGORY,EBITDA COHORT,GM_PCT,EBITDA_PCT,AOV,VARIANCE_PCT,VARIANCE_CATEGORY,DISCOUNT_PCT
0,2023-10-01,Ahmedabad,Ramos-Martin,Inactive,West,14270,6554333.68,1163493.98,5434068.17,1763679.62,...,INR 20 to 30 lacs,0% to 10%,EBITDA +ve,More than 20%,66.520096,43.704173,380.803656,1.681973,Var <2%,17.751522
1,2023-10-01,Ahmedabad,Drake LLC,Active,North,12361,3971544.22,888746.33,3158828.94,1271805.20,...,INR 30 to 40 lacs,More than 30%,EBITDA -ve,More than 20%,57.690179,7.984438,255.548009,1.413911,Var <2%,22.377853
2,2023-10-01,Pune,"Thomas, Dean and Kelley",Inactive,East,11021,4202495.56,1123306.62,3196270.28,1372216.47,...,INR 30 to 40 lacs,More than 30%,EBITDA -ve,More than 20%,53.215513,9.420520,290.016358,1.476725,Var <2%,26.729514
3,2023-10-01,Hyderabad,Smith-Bradley,Inactive,West,12706,5709492.69,1513926.48,4279244.35,1840266.70,...,INR 30 to 40 lacs,10% to 20%,EBITDA +ve,10% to 20%,54.413874,26.571278,336.789261,1.435131,Var <2%,26.515954
4,2023-10-01,Hyderabad,Stone Ltd,Active,South,14760,4960664.78,889983.70,4150072.32,1721686.18,...,More than 40 lacs,0% to 10%,EBITDA +ve,10% to 20%,56.899265,26.678009,281.170211,1.101653,Var <2%,17.940815

In [96]:
##Discount vs EBITDA
import plotly.express as px
fig = px.scatter(cd, x="DISCOUNT",y="EBITDA_PCT",color="CITY",hover_data=["STORE"],title="Discount vs EBITDA %"
)
fig.show()

In [97]:
cd["EBITDA_PCT"].head()

0    43.704173
1     7.984438
2     9.420520
3    26.571278
4    26.678009
Name: EBITDA_PCT, dtype: float64

In [98]:
cd["DISCOUNT_PCT"].head()

0    17.751522
1    22.377853
2    26.729514
3    26.515954
4    17.940815
Name: DISCOUNT_PCT, dtype: float64

In [99]:
fig=px.scatter(cd,x="DISCOUNT_PCT",y="EBITDA_PCT",color="CITY",hover_data=["STORE"],trendline="ols",
title="Discount % vs EBITDA %"
)
fig.show()

In [100]:
#How is business revenue changing month-over-month?
monthly_revenue = (
    cd.groupby("MONTH")["NET REVENUE"]
    .sum()
    .reset_index()
)

In [101]:
fig = px.line(
    monthly_revenue,
    x="MONTH",
    y="NET REVENUE",
    markers=True,
    title="Monthly Revenue Trend"
)
fig.show()

In [102]:
#Is profitability improving over time?
monthly_ebitda = (
    df.groupby("MONTH")["KITCHEN EBITDA"]
    .sum()
    .reset_index()
)

In [103]:
fig = px.line(
    monthly_ebitda,
    x="MONTH",
    y="KITCHEN EBITDA",
    markers=True,
    title="Monthly EBITDA Trend"
)

fig.show()

In [104]:
#Which cities are most profitable?
city_ebitda = (
    df.groupby("CITY")["KITCHEN EBITDA"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

In [105]:
fig = px.bar(
    city_ebitda,
    x="CITY",
    y="KITCHEN EBITDA",
    title="City-wise EBITDA"
)

fig.show()

In [106]:
#Which stores contribute most to profitability?
top_stores = (
    df.groupby("STORE")["KITCHEN EBITDA"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)

In [107]:
fig = px.bar(
    top_stores,
    x="KITCHEN EBITDA",
    y="STORE",
    orientation="h",
    title="Top 10 Stores by EBITDA"
)

fig.show()

In [108]:
#Does food wastage reduce profitability?
fig = px.scatter(
    df,
    x="VARIANCE_PCT",
    y="EBITDA_PCT",
    color="CITY",
    hover_data=["STORE"],
    title="Variance % vs EBITDA %"
)

fig.show()

In [109]:
corr = cd.corr(numeric_only=True)
corr

,ORDER COUNT,CART SALES,DISCOUNT,NET REVENUE,IDEAL FOOD COST,GROSS MARGIN,KITCHEN EBITDA,VARIANCE,GM_PCT,EBITDA_PCT,AOV,VARIANCE_PCT,DISCOUNT_PCT
ORDER COUNT,1.000000,0.815089,0.632825,0.798059,0.701087,0.739881,0.730200,0.008403,0.040349,0.684957,-0.032371,-0.498921,-0.031671
CART SALES,0.815089,1.000000,0.786537,0.975756,0.846600,0.911321,0.900463,-0.015895,0.066057,0.819179,0.500672,-0.598101,-0.022250
DISCOUNT,0.632825,0.786537,1.000000,0.633610,0.542572,0.596614,0.588504,0.005054,0.051615,0.546543,0.185338,-0.387621,0.580899
NET REVENUE,0.798059,0.975756,0.633610,1.000000,0.869713,0.932511,0.921845,-0.022012,0.065547,0.835034,0.563465,-0.612915,-0.231680
IDEAL FOOD COST,0.701087,0.846600,0.542572,0.869713,1.000000,0.634512,0.628388,0.000194,-0.413694,0.522098,0.481589,-0.674197,-0.208659
GROSS MARGIN,0.739881,0.911321,0.596614,0.932511,0.634512,1.000000,0.987902,-0.034416,0.409874,0.930373,0.530589,-0.469321,-0.211742
KITCHEN EBITDA,0.730200,0.900463,0.588504,0.921845,0.628388,0.987902,1.000000,-0.034194,0.402379,0.951905,0.526859,-0.465831,-0.211059
VARIANCE,0.008403,-0.015895,0.005054,-0.022012,0.000194,-0.034416,-0.034194,1.000000,-0.034401,-0.020995,-0.046794,0.657404,0.026036
GM_PCT,0.040349,0.066057,0.051615,0.065547,-0.413694,0.409874,0.402379,-0.034401,1.000000,0.491128,0.053898,0.273981,-0.009182
EBITDA_PCT,0.684957,0.819179,0.546543,0.835034,0.522098,0.930373,0.951905,-0.020995,0.491128,1.000000,0.485915,-0.416579,-0.196728
AOV,-0.032371,0.500672,0.185338,0.563465,0.481589,0.530589,0.526859,-0.046794,0.053898,0.485915,1.000000,-0.362896,-0.353589
VARIANCE_PCT,-0.498921,-0.598101,-0.387621,-0.612915,-0.674197,-0.469321,-0.465831,0.657404,0.273981,-0.416579,-0.362896,1.000000,0.156669
DISCOUNT_PCT,-0.031671,-0.022250,0.580899,-0.231680,-0.208659,-0.211742,-0.211059,0.026036,-0.009182,-0.196728,-0.353589,0.156669,1.000000

In [110]:
##Business Meaning from above matrix:
#Higher revenue kitchens generally produce higher EBITDA.
#Gross margin efficiency is the strongest determinant of profitability.
#Higher food wastage tends to reduce profitability.
#Aggressive discounting appears to pressure margins.
#Stores with higher average order values tend to be more profitable."AOV ↔ EBITDA_PCT = 0.49"
#Order volume is a major revenue growth driver.
#Higher revenue kitchens appear operationally more efficient and experience lower food wastage percentages.

In [1]:
cd.head()

NameError: name 'cd' is not defined